### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by dwillmore** [dbuezas/lgt8fx#12]
I love the addition of the boards section in the readme.md.  Could you change the titles of the section and each board to point to the boards wiki page and the individual board wiki pages where they exist?  That would make it easier for users to find board specific information.

**Comment by dbuezas** [comment]
Wow, the individual boards in the wiki have a lot of info!
I'll link to then

**Comment by dwillmore** [comment]
I like your changes.  They look exactly like I had in mind!  Thank you, sir!
