### ISSUE TITLE
Dose not seem to work in the Arduino IDE 2.0.0 beta 7

### ISSUE THREAD

**Issue by derekchall** [dbuezas/lgt8fx#171]
If the URL is added to the IDE beta, the boards do not appear in the board manager, works OK in 1.8.13
Other board URLs seem ok.

**Comment by LaZsolt** [comment]
Today I tried Arduino IDE 2.0.0 RC3. I added the lgt8fx URL in the Preferences box. It appeared and after the install, it worked fine in the IDE. Blink compile was successful.

**Comment by derekchall** [comment]
Thanks its  working now
