### ISSUE TITLE
use with Void Linux arduino package

### ISSUE THREAD

**Issue by jg1uaa** [dbuezas/lgt8fx#177]
Void Linux's arduino package specifies `compiler.path=/usr/bin/` in /usr/lib/arduino/hardware/arduino/avr/platform.txt and use /usr/bin/avr-g++ (in avr-gcc package).

We cannot simply install lgt8fx package into void's arduino. After installing, we have to fix platform.txt; replace `compiler.path={runtime.avr-gcc.path}/bin/` to `compiler.path=/usr/bin/` .

Maybe no need to care. Simply add notes to suitable document, I think.

**Comment by dwillmore** [comment]
You might be better off finding out hoe runtime.avr-gcc.path is set and altering that.  There may be a better way for that code to detect your distirbution.
