### ISSUE TITLE
how to manually add supporting of lgt8f328d 19200  upload speed support

### ISSUE THREAD

**Issue by youxiaojie** [dbuezas/lgt8fx#19]
1.because of GFW, the raw.githubusercontent.com was banned.
 C:\Users\Allan>ping raw.githubusercontent.com
Ping 请求找不到主机 raw.githubusercontent.com。请检查该名称，然后重试。
so how to use downloaded v1.05 release manully? thanks.

2. I am using a lgt8f328d and the pin is the same as arduino nano, however the bootloader maybe using 19200 baud, so that the upload is failuer , how to modify it? and is it an viarient? if it is can we add it in viarent list?
[https://item.taobao.com/item.htm?spm=a230r.1.14.86.70b3549eTvx45q&id=591048490054&ns=1&abbucket=14#detail](url)
is it possible to changed to default baud?57600? must I reburn bootloader to do so?

and I am in china, I see you meet some difficult on https://github.com/dbuezas/lgt8fx/issues/9#issuecomment-554247316, mentioned a forum, what can I do for you?

the backside of five pin labelled gnd vcc swd rst swc, seems jtag, not serial.

**Comment by youxiaojie** [comment]
got it! 
Manually install:
1.download package_lgt8fx_index.json
2.palce it into C:\Users\Allan\AppData\Local\Arduino15
3.doanload hw support release file from https://github.com/dbuezas/lgt8fx/releases
4.uppack it to C:\Users\Allan\AppData\Local\Arduino15\staging\packages
5.click install in board manager. or unpack hw support file to C:\Users\Allan\AppData\Local\Arduino15\packages\LGT8fx Boards\hardware\avr\<version>\
here <version> is like 1.0.5
6 modify C:\Users\Allan\AppData\Local\Arduino15\packages\LGT8fx Boards\hardware\avr\<version>\boards.txt

adding these lines:

328.menu.variant.modelD=328D-B19200 (BTE17-11 19200 Baud)
328.menu.variant.modelD.bootloader.path=lgt8fx8e
328.menu.variant.modelD.bootloader.file=lgt8fx8e/optiboot_lgt8f328d.hex
328.menu.variant.modelD.build.variant=lgt8fx8e
328.upload.speed=19200

**Comment by alpharesearch** [comment]
I ordered some "Acxico 5Pcs 5V 16M LGT8F328P-LQFP32 MiniEVB for Arduino Nano V3.0 HT42B534-1 Replace ATMeag328P" here in the USA on Amazon with the same 19200 baud rate requirements. I guess I could update the boot loader but it would be nice if there were some baud rate drop-down settings like on other boards.

**Comment by youxiaojie** [comment]
you can try different the baud rate, may be the boot loader is custom.my 19200 is a nonstandard bootloader viariant.  you can try 115200 78600 etc

**Comment by alpharesearch** [comment]
Thanks youxiaojie for your solution. The download works with your settings. Looks like I have the same BTE17-11 board like you. I cannot get my board to work with 32 Mhz, do you have any problems like this?

**Comment by youxiaojie** [comment]
it seem that the 16Mhz version is the outdated 328d, equally to mega 168 though marked with "328", only with 16Mhz, 32Mhz does not work.

**Comment by dwillmore** [comment]
If any of you with variant boards would be so kind as to take some nice pictures of them and include a link to where you got them, I'll add it to the wiki so that others can benefit.

**Comment by youxiaojie** [comment]
agree!

**Comment by alpharesearch** [comment]
Here is the link I bought it from:
https://www.amazon.com/dp/B0837GNYY2/
And here is the photo:
https://imgur.com/gallery/a7dQ5R0
https://imgur.com/gallery/QcfuSw5

**Comment by youxiaojie** [comment]
from here:
https://item.taobao.com/item.htm?spm=a1z09.2.0.0.1c932e8dKugRs3&id=575845863557&_u=igtqrcba22

**Comment by dbuezas** [comment]
Interesting, I wasn't aware of the "nano style" board with the 328d variant. I guess I've been lucky and always got 328p's.
BTW, as @youxiaojie said, this variant cant handle 32MHz even though it has a 32MHz internal clock.
From the datasheet:
>LGT8FX8D maximum operating frequency of 20MHz, so when the choice of internal 32MHz RC as the main clock source, be sure to
Make sure CLKPR is set to the correct frequency division (minimum 2).

**Comment by dbuezas** [comment]
I'll welcome a PR with the added support for this board

**Comment by dwillmore** [comment]
Does this issue require further effort?

**Comment by LaZsolt** [comment]
I my opinion no need futher effort.
With the new board selection menu in case of selecting generic board ( `LGT8F328 + 16 MHz crystal` ) the upload speed selection available.

**Comment by dwillmore** [comment]
Okay, that's that I had concluded, but I hadn't been a participant to this converstaion, so I didn't feel right in closing it.  I'll do that now.
