### ISSUE TITLE
Linking problem on Arduino 1.8.19

### ISSUE THREAD

**Issue by tistructor** [dbuezas/lgt8fx#208]
Linking problem under arduino 1.8.19:

 /mnt/DFA9A0176612163D/DATA/ProgramsLinux/Arduino/ArduinoIde/hardware/tools/avr/bin/../ lib / gcc / avr / 7.3.0 /../../../../ avr / bin / ld: / mnt / DFA9A0176612163D / DATA / ProgramsLinux / Arduino / ArduinoIde / hardware / tools / avr / bin /../libexec/gcc/avr/7.3.0/liblto_plugin.so: error loading plugin: / mnt/DFA9A0176612163D/DATI/ProgrammiLinux / Arduino / ArduinoIde / hardware / tools / avr / bin /../libexec/gcc/avr/7.3.0/liblto_plugin.so: file too short
collect2: error: ld returned 1 exit status
exit status 1
Error filling for board LGT8F328.

**Comment by tistructor** [comment]
which version of arduino ide should be used?

**Comment by tistructor** [comment]
I am using it under linux. As I have a moment of time I test.

**Comment by tistructor** [comment]
With arduino 1.8.12 I do not find problems but with version 1.8.19 I find compilation problems.

**Comment by tistructor** [comment]
No, it's my problem. I downloaded version 1.8.19 with clean installation and I have no compilation problems. 
I will have garbage somewhere in the installations.
Strange however with other devices I have never encountered problems.  Thanks

**Comment by tistructor** [comment]
I understand the problem. If you change the warnings of the compiler other than none, the compilation is not successful.

**Comment by dwillmore** [comment]
It appears this was an issue with the users environment and not this library, correct?  If so, we should close this.
