### ISSUE TITLE
Nano 328P-LGFP32 V3.1

### ISSUE THREAD

**Issue by biblical-text** [dbuezas/lgt8fx#210]
![board](https://user-images.githubusercontent.com/88878602/171851181-4d6ba4c8-eae4-4467-9650-c4efdfa3baf1.jpg)

I purchased this thinking it was a standard Arduino Nano, and I can actually deploy from the Arduino IDE using the "Arduino Nano" setting. But I can't deploy to it using any of the options from this library. Should I be able to? I tried every menu option and  it always returns the dreaded:

```
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
```

On a side note, when I use it using the "Arduino Nano" settings, Serial.begin(9600) in the code, actually appears to send data at 2400. I am very curious about what is going on there.

**Comment by LaZsolt** [comment]
The upload speed is 115200 baud for this board.
You may select this upload speed if you install the pre release of lgt8fx package:
https://github.com/dbuezas/lgt8fx/discussions/207

You need to select a custom board: LGT8F328 + 16 MHz crystal
but your board has no external crystal so you need to select one of the internal frequencies.

![kép](https://user-images.githubusercontent.com/60486174/171873443-ae3669ed-0947-42ab-82e5-9fc5f2b543ba.png)

**Comment by demosspro** [comment]
> The upload speed is 115200 baud for this board. You may select this upload speed if you install the pre release of lgt8fx 
Hello! Is Daniel here and we  can comit some changes? Do you have some contacts with him? lgt8f328p is good chip and i do some cool things with it. I would be grateful if we could develop it further with you!

**Comment by dwillmore** [comment]
Does this still persist in 1.0.7 release?

**Comment by dbuezas** [comment]
Closing as stale
