### ISSUE TITLE
LGT8F328P-nano as isp

### ISSUE THREAD

**Issue by orabeidm** [dbuezas/lgt8fx#225]
vcan i use LGT8F328P-nano as isp for arduino nano?

**Comment by orabeidm** [comment]
![photo_2022-11-24_20-27-59](https://user-images.githubusercontent.com/60073650/203840233-45dbb504-8e44-4ede-b76d-9976742aa2bc.jpg)

**Comment by jayzakk** [comment]
One of the first results on Google reveal: https://youtu.be/KMzk5gsDQMc

**Comment by LaZsolt** [comment]
Maybe this is the answer for you: https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP
Use your LGT8F328P as a programmer and the classic nano3 as a target.

**Comment by LaZsolt** [comment]
And one more. Try tu use this: https://github.com/dbuezas/lgt8fx/discussions/207

**Comment by orabeidm** [comment]
> 



> One of the first results on Google reveal: https://youtu.be/KMzk5gsDQMc
> 
> Double check the question and answer on the video.

Yes, and in the comments we communicate with the creator of the video)))

**Comment by orabeidm** [comment]
> Maybe this is the answer for you: https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP
> Use your LGT8F328P as a programmer and the classic nano3 as a target.

it doesn't work i checked

**Comment by LaZsolt** [comment]
> it doesn't work i checked

In v1.0.6 the delayMicroseconds() about 30% shorter than requested. Use the pre-release of v1.07 : #207
