### ISSUE TITLE
Incorrectly named voltage reference

### ISSUE THREAD

**Issue by thegoodhen** [dbuezas/lgt8fx#23]
Hello, the  INTERNAL2V56 voltage is defined, although the device has no such reference. Is this intentional?

**Comment by LaZsolt** [comment]
According to database LGT8Fx8D series MCU has internal 1.25V / 2.56V ± 1% calibrated reference voltage source.

**Comment by dbuezas** [comment]
Yes, you are right @thegoodhen and also partially @LaZsolt.
According to the datasheet, the available internal references are:
- 1.024V
- 2.048V
- 4.096V

But the core has these constants available:
- #define INTERNAL 3
_- #define INTERNAL1V25 3_
- #define INTERNAL2V56 2
_- #define INTERNAL1V024 3_
- #define INTERNAL2V048 2
- #define INTERNAL4V096 4
[here](https://github.com/dbuezas/lgt8fx/blob/db47042686b2c9455a7690ca98712c6e8514871c/lgt8f/cores/lgt8f/Arduino.h#L82-L87)

The ones in _italic_ are just aliases of the nearest ones. They were there in the original core this one derives from so I assume they are there for compatibility (as they are kinda close).

Thanks for the issue anyway :)
