### ISSUE TITLE
Forks create updates...

### ISSUE THREAD

**Issue by holgerlembke** [dbuezas/lgt8fx#231]
I don't think it is a good idea to include all the automatic stuff into forks. At least my fork now makes updates as crazy with every push. 

Is it .gitignore to be used in the upstream?

**Comment by dbuezas** [comment]
Good point. A work around is to deactivate actions in your fork, or to remove the files inside .github/workflows.

But to reduce friction, I disabled releases on commits (releases will only happen when PRs get merged now.

**Comment by dbuezas** [comment]
On top of that, actions will only run in this repo now, and not it forks. Change: https://github.com/dbuezas/lgt8fx/commit/4c1d9e494f2e2778bed7a44a1298bd93174b1e72

**Comment by holgerlembke** [comment]
Thats the way I like it.
