### ISSUE TITLE
NO SSL for json file

### ISSUE THREAD

**Issue by Digitcom-srls** [dbuezas/lgt8fx#253]

**Comment by dbuezas** [comment]
What fo you mean? 

It is https

https://raw.githubusercontent.com/dbuezas/lgt8fx/master/package_lgt8fx_index.json

**Comment by Digitcom-srls** [comment]
![image](https://user-images.githubusercontent.com/68905819/226692898-4737405d-a703-4413-96fb-19cae55df7b6.png)

**Comment by dwillmore** [comment]
I'm looking at it right now and the github.com key is signed by digicert and is completely valid.  

Possibly you're at a school or business which is monitoring SSL traffic and they are substituting a different certificate and doing it wrong?  Can you show the information page about the certificate that your browser has been presented?

**Comment by Digitcom-srls** [comment]
![image](https://user-images.githubusercontent.com/68905819/226698777-57ad2ee8-4193-47c6-8c0a-84244e9c4fab.png)

**Comment by Digitcom-srls** [comment]
I fixed it by downloading the json file with my mobile phone and uploading it to a webserver in localhost.

**Comment by jayzakk** [comment]
This is a fake certificate from somewhere in your network chain, maybe even some local firewall or antivirus scanner.

GitHub sends a very valid certificate. If not, millions of user would have problems.
