### ISSUE TITLE
Internal clock speeds less than 32MHz no longer available since version 2.0.3.

### ISSUE THREAD

**Issue by VE5BNC** [dbuezas/lgt8fx#287]
Hi

Since the menus were reorganized in version 2.0.3 the only internal clock speed available is 32 MHz.  My testing showed that the internal clock speeds as low as 8 MHz worked correctly in version 2.0.2 (I didn't test any lower than 8 MHz).  Some of my projects run at 8 MHz.  Can these lower internal clock speeds be added again?

Thanks

Bruce

**Comment by LaZsolt** [comment]
If you choose the 32 Mhz internal RC clock and divider 4, the 8 MHz CPU clock is given. Is that right for you?

![kép](https://github.com/dbuezas/lgt8fx/assets/60486174/b5528f69-19c3-4979-ae4c-7d4328db6e78)

**Comment by VE5BNC** [comment]
Hi

Thanks for the quick reply and suggestion.

I didn't realize that was the effect of the clock divider.  I'll test that
and let you know.

Bruce

**Comment by VE5BNC** [comment]
Hi

I just tested using the clock divider and it works perfectly.

Thanks

Bruce
