### ISSUE TITLE
LGT8F Lock Bits

### ISSUE THREAD

**Issue by WGR7** [dbuezas/lgt8fx#30]
Hi
Can this ISP burn the lock bits? Is the lgt8f lock bits the same as ATMega? Do  read out protection work by the same manner as ATMega?

Regards

**Comment by dbuezas** [comment]
I couldn't find anything on lock bits for this board in the datasheet

**Comment by WGR7** [comment]
I guess the LGTMix can program the Readout protection. I've found on file of Migrating from Atmega to LGT8F88 that says that they use a different aproach.

ftp://imall.iteadstudio.com/Microcontroller/IM131218002/Migrating_from_ATmega88_to_LGT8F88A_v1.0.pdf

**Comment by dwillmore** [comment]
Is anyone is looking for a simple project, this issue may be what you're looking for.

**Comment by LaZsolt** [comment]
Since LGT8Fx has no lock bits, it is not an issue.
I think it could be mentioned in the ~~documentation~~ readme, as a negative feature.

**Comment by dbuezas** [comment]
I mentioned it in the readme now
