### ISSUE TITLE
renew core code (ArduinoCore-avr 1.8.3 based)

### ISSUE THREAD

**Issue by jg1uaa** [dbuezas/lgt8fx#38]
Current core code is based on old (arduino-1.5.x?) code and it has some bugs.
I merged ArduinoCore-avr 1.8.3 to core/ directory on my repo, https://github.com/jg1uaa/lgt8fx/tree/arduinocoreavr-183/lgt8f/cores/lgt8f .

If there is no problem, I will renew other directory.

**Comment by jg1uaa** [comment]
is there any branch to send PR?

**Comment by dbuezas** [comment]
Hi!
Master branch is good.
I have quite some PRs to check and merge now. I'll get to it as soon as I get some free time 👍

**Comment by jg1uaa** [comment]
Ok, I sent PR to master branch. Please review if you have enough time. Regards,

**Comment by dbuezas** [comment]
Merged
