### ISSUE TITLE
do we have an "official" community forum somewhere ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [dbuezas/lgt8fx#62]
Hello,

Do we have an "official" community forum available somewhere so we could discuss and share LGT8 related information, idea, experiences and projects ? 

If not, could you, @dbuezas, open a dedicated repository on your Github where we could use the "Issues" as a forum board ?

**Comment by dbuezas** [comment]
I like the idea!

https://github.com/dbuezas/lgt8fx-forum

**Comment by seisfeld** [comment]
I suggest activating the discussions feature on this repo and remove the lgt8fx-forum again. This way it's all in the same place. Here's how its activated on the main settings page:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/9606362/103083283-51a7b880-45dc-11eb-8625-034e78844dc9.png">

**Comment by dbuezas** [comment]
I activated discussions now, thanks for the tipp Stephan!
Do you know if there is a way to import the issues from the forum repo?

**Comment by seisfeld** [comment]
I don't know. Maybe when you first transfer the issues into the main repo and then transfer them into discussions? Would that be possible? I never worked with the discussion feature...

**Comment by SuperUserNameMan** [comment]
Also, how do we enable notification to know when a new discussion or answer is created ?

https://github.com/dbuezas/lgt8fx/discussions

**Comment by dbuezas** [comment]
To watch discussions, I hope this does the trick:
https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository

**Comment by dbuezas** [comment]
@SuperUserNameMan:
![image](https://user-images.githubusercontent.com/777196/108167826-96d8fa00-70f6-11eb-84ba-5ffe2ab14acc.png)
![image](https://user-images.githubusercontent.com/777196/108167855-a2c4bc00-70f6-11eb-9708-273140be05b3.png)

**Comment by dbuezas** [comment]
Closing this issue now.
All issues in the forum repo have been transferred to this one and converted into discussions.
Thanks for originating this idea and following up! 🥇
