### ISSUE TITLE
 some third party library expect SoftwareSerial_h to be defined

### ISSUE THREAD

**Issue by SuperUserNameMan** [dbuezas/lgt8fx#65]
Hello @jg1uaa 

Apparently, some libraries expect macro ``SoftwareSerial_h`` to be defined after an ``#include <SoftwareSerial.h>``. (found that thanks to this post on the forum [here](https://github.com/dbuezas/lgt8fx-forum/issues/3) ).

Our brand new SoftwareSerial library defines ``SoftwareSerialLGT_h`` instead. 

Maybe could define ``SoftwareSerial_h`` too ?

**Comment by jg1uaa** [comment]
sorry for late reply, I think this is need to fix but I don't know why LGT-specific SoftwareSerialLGT_h is defined.

If there is no problem, I want to replace SoftwareSerialLGT_h to (standard) SoftwareSerial.h. That code is modified for LGT8Fx but work same as for AVR's.

**Comment by dbuezas** [comment]
@jg1uaa I think that's a great idea, go for it! :)

**Comment by LaZsolt** [comment]
I don't want to be indecent. Would you make a pull request?

**Comment by dwillmore** [comment]
Was this included and, if so, could this issue be closed?

**Comment by dbuezas** [comment]
Yes, I see the change in master. Closing...
