### ISSUE TITLE
Suggestion to include "LGT SDK Builder" under "docs & links"

### ISSUE THREAD

**Issue by sengiv** [dbuezas/lgt8fx#73]
I find the "LGT SDK Builder" very useful during development, hopefully others can find it helpful too.

Links:
Document page : http://www.lgtic.com/2017/11/11/lgtsdk_builder/
Download link : http://www.lgtic.com/upload/tools/lgtsdk_builder/LGTSDK_Builder_latest.rar

PS: Just want to say thanks for this git, helped me a lot!

**Comment by dbuezas** [comment]
done :)
