### ISSUE TITLE
remove this repo and activate discussions feature on main repo

### ISSUE THREAD

**Issue by seisfeld** [dbuezas/lgt8fx#95]
@dbuezas I suggest activating the discussions feature on the main lgt8fx repo and remove the lgt8fx-forum repo again. This way it's all in the same place. Here's how its activated on the main settings page:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/9606362/103083283-51a7b880-45dc-11eb-8625-034e78844dc9.png">

**Comment by dbuezas** [comment]
Thanks again for pointing this out! I've transferred all issues to the main repo and made them into discussions 🙏
